name = "BornSampling"
uuid = "024a6725-e534-4d5f-9c4f-99bb86a2a22e"
authors = ["Qiaoyi Li <liqiaoyi@itp.ac.cn>"]
version = "0.1.0"

[deps]
FiniteMPS = "6b572690-f317-4dad-a5fe-5fe73a0b7d42"
FiniteMPSTangents = "a8aeb656-834f-4cb3-ac9f-857a8aeda547"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[sources]
FiniteMPSTangents = {url = "https://github.com/Qiaoyi-Li/FiniteMPSTangents.jl", rev = "49d784b69646540ea71a90ad425854839d6fb35e"}

[compat]
FiniteMPS = "1.8.3"
FiniteMPSTangents = "0.1"
LinearAlgebra = "1.11"
Random = "1.11"
Serialization = "1.11"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
